/// Calendar dimension marked as a date table so DAX time intelligence works.
table DIM_DATE
	lineageTag: 7fe1d7e5-7d6e-5b87-9c35-124f14ed4c40
	dataCategory: Time

	column DATE_KEY
		dataType: double
		formatString: 0
		lineageTag: 69550467-c2b5-514d-940a-f116a332f402
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

	column FULL_DATE
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 0ff79f81-bf53-5ace-bccd-397bf5b66f65
		summarizeBy: none
		sourceColumn: FULL_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DAY_OF_MONTH
		dataType: double
		formatString: 0
		lineageTag: 3a5c479d-2052-5517-bef0-ae02f1b3ec3d
		summarizeBy: sum
		sourceColumn: DAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

	column DAY_OF_WEEK
		dataType: double
		formatString: 0
		lineageTag: 9b77c7fd-9002-5738-a304-d72fbf404b0f
		summarizeBy: sum
		sourceColumn: DAY_OF_WEEK

		annotation SummarizationSetBy = Automatic

	column DAY_NAME
		dataType: string
		lineageTag: 7126a465-4ee5-572d-a483-0f9697b199b3
		summarizeBy: none
		sourceColumn: DAY_NAME

		annotation SummarizationSetBy = Automatic

	column IS_WEEKEND
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0a710333-974d-5332-8a33-8c934e5ced2e
		summarizeBy: none
		sourceColumn: IS_WEEKEND

		annotation SummarizationSetBy = Automatic

	column MONTH_NUMBER
		dataType: double
		formatString: 0
		lineageTag: 76f48f33-21e0-5959-98b6-17f53426b7c5
		summarizeBy: sum
		sourceColumn: MONTH_NUMBER

		annotation SummarizationSetBy = Automatic

	column MONTH_NAME
		dataType: string
		lineageTag: ccf26bc3-5100-5b55-99ae-84037917ec7c
		summarizeBy: none
		sourceColumn: MONTH_NAME
		sortByColumn: MONTH_NUMBER

		annotation SummarizationSetBy = Automatic

	column MONTH_YEAR
		dataType: string
		lineageTag: 41188716-575c-55a1-a1b7-a0ff1d3c2e42
		summarizeBy: none
		sourceColumn: MONTH_YEAR
		sortByColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

	column QUARTER_NUMBER
		dataType: double
		formatString: 0
		lineageTag: 1b0b5d29-f6cc-5de3-b916-d29c8debf99d
		summarizeBy: sum
		sourceColumn: QUARTER_NUMBER

		annotation SummarizationSetBy = Automatic

	column QUARTER_NAME
		dataType: string
		lineageTag: d7815c3c-4635-5e30-b7f6-fa44b15b8719
		summarizeBy: none
		sourceColumn: QUARTER_NAME

		annotation SummarizationSetBy = Automatic

	column YEAR_NUMBER
		dataType: double
		formatString: 0
		lineageTag: c66349f9-3a6c-5786-a401-bec5f62e7688
		summarizeBy: sum
		sourceColumn: YEAR_NUMBER

		annotation SummarizationSetBy = Automatic

	column FISCAL_YEAR
		dataType: double
		formatString: 0
		lineageTag: 32aa3041-0b17-5235-8e9f-63a7087ba08a
		summarizeBy: sum
		sourceColumn: FISCAL_YEAR

		annotation SummarizationSetBy = Automatic

	column FISCAL_QUARTER
		dataType: double
		formatString: 0
		lineageTag: e7127287-f194-539b-ada3-cb127110749f
		summarizeBy: sum
		sourceColumn: FISCAL_QUARTER

		annotation SummarizationSetBy = Automatic

	column FISCAL_PERIOD
		dataType: double
		formatString: 0
		lineageTag: 9a744657-a1b0-5f86-adca-a603e65e41f5
		summarizeBy: sum
		sourceColumn: FISCAL_PERIOD

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("CEMNFKN-TT95210.snowflakecomputing.com", "FIN_PROC_WH"),
				    Db = Source{[Name="FIN_PROC_DB",Kind="Database"]}[Data],
				    Sch = Db{[Name="GOLD",Kind="Schema"]}[Data],
				    Data = Sch{[Name="DIM_DATE",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Data,{{"FULL_DATE", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

